# -*- coding: utf-8 -*-
"""CalculoValorCNH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10cmq-KwlmlhioiaFfskqRWWnCcH0H2pw
"""

#FUNÇÕES DO SOFTWARE

def validar_idade(idade):
  if idade < 18:
    print('\nDesculpe, você não tem idade para prosseguir,', nome)
    return False
  else:
    print('\nÓtimo! Podemos prosseguir,', nome)
    return True

def escolher_carta():
  print("""Digite uma das opções abaixo:
    1 - Carro
    2 - Moto
    3 - Carro e Moto""")
  return int(input())

def calcular_preco(escolha):
  valor_carro = 1500
  valor_moto = 1000

  if escolha == 1:
    return valor_carro
  elif escolha == 2:
    return valor_moto
  else:
    return valor_carro + valor_moto

def desconto(valor):
  return valor - (valor * 0.10)

#SOFTWARE

nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))

if validar_idade(idade):
  escolha = escolher_carta()

  print('\nPerfeito! Vou calcular o valor')
  valor = calcular_preco(escolha)

  print('\n'+nome, 'o valor total é de R$', valor)
  print('Mas vou ver com meu gerente se posso dar um desconto...')
  valor = desconto(valor)

  print('\nCom desconto eu consigo fazer por R$', valor)

  print("""Te interessa?
    1 - Sim
    2 - Não""")
  interesse = int(input())
  if interesse == 1:
    print('\nPerfeito! Começaremos amanhã!')
  else:
    print("""\nTudo bem!
      Me avise se mudar de ideia.""")